### ISSUE TITLE
Image use

### ISSUE THREAD

**Issue by ngscheurich** [dstaley/brslack.com#5]
Hey, @dstaley. I need a nice Baton Rouge photo for a community project I'm working on. Is https://github.com/dstaley/brslack.com/blob/c5364fd4479a47e45083711aa10710850fbdfa37/img/background_1440%402x.jpg up for grabs? If so, what's the license like?

**Comment by dstaley** [comment]
It is! You can find the original [here](https://www.flickr.com/photos/33630741@N07/11941978643). It's Creative Commons.

**Comment by ngscheurich** [comment]
Perfect! Thanks. Hope you've been well.
